CREATE DATABASE [EFCoreOnNet5]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'EFCoreOnNet5', FILENAME = N'C:\Users\You\Source\Repos\EFCoreOnNet5.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'EFCoreOnNet5_log', FILENAME = N'C:\Users\You\Source\Repos\EFCoreOnNet5_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
USE [EFCoreOnNet5]
GO
